# This is the default configuration.
# Please make a copy of this file and put it into your project's root directory,
# replacing any fields with your own values. Fields which are empty or nonexistant
# will be filled with the default values listed here.

# All directories are relative to your current (project root) directory.


project_version : 0.1
project_author : "4DN-DCIC"
project_name : "4D Nucleome Portal"  # Project Name

output_directory : "../4dn_portal_gh_pages/"         # Save output here

python_project_directory : "./src/encoded"
javascript_root_directory : "./src/encoded/static/components/item-pages" # Fourfront JS directory

# Define what each section in nav-menu contains.
sections : [
    {
        "title" : "Getting Started",
        "path" : "./README.rst",
        "saveAs" : "README.rst"
    },
    {
        "title" : "Overview",
        "path" : "./docs/overview.rst",
        "saveAs" : "overview.rst"
    },
    {
        "title" : "ElasticBeanstalk Deployment",
        "path" : "./docs/beanstalk-deployment.md",
        "saveAs" : "beanstalk-deployment.md"
    },
    {
        "title" : "Database Overview",
        "path" : "./docs/database.rst",
        "saveAs" : "database.rst"
    },
    {
        "title" : "Object Lifecycle",
        "path" : "./docs/object-lifecycle.rst",
        "saveAs" : "object-lifecycle.rst"
    },
    {
        "title" : "Authentication",
        "path" : "./docs/auth.rst",
        "saveAs" : "authentication.rst"
    },
    {
        "title" : "Document Invalidation",
        "path" : "./docs/invalidation.rst",
        "saveAs" : "invalidation.rst"
    }
]

python_sys_inserts : [
    "./eggs/SPARQLWrapper-1.7.6-py3.6.egg",
    "./src",
    "./eggs/pyramid-1.6a2-py3.6.egg",
    "./eggs/waitress-0.8.10-py3.6.egg",
    "./eggs/psycopg2-2.6.1-py3.6-macosx-10.12-x86_64.egg",
    "./eggs/repoze.debug-1.0.2-py3.6.egg",
    "./eggs/setuptools-18.1-py3.6.egg",
    "./eggs/rutter-0.2-py3.6.egg",
    "./eggs/pyramid_translogger-0.1-py3.6.egg",
    "./eggs/WebOb-1.6.0-py3.6.egg",
    "./eggs/PasteDeploy-1.5.2-py3.6.egg",
    "./eggs/translationstring-1.3-py3.6.egg",
    "./eggs/venusian-1.0.1.dev40-py3.6.egg",
    "./eggs/zope.deprecation-4.1.2-py3.6.egg",
    "./eggs/zope.interface-4.1.3-py3.6-macosx-10.12-x86_64.egg",
    "./eggs/repoze.lru-0.6-py3.6.egg",
    "./eggs/PyJWT-1.4.2-py3.6.egg",
    "./eggs/zope.sqlalchemy-0.7.6-py3.6.egg",
    "./eggs/xlrd-0.9.4-py3.6.egg",
    "./eggs/subprocess_middleware-0.3-py3.6.egg",
    "./eggs/strict_rfc3339-0.6-py3.6.egg",
    "./eggs/simplejson-3.8.2-py3.6-macosx-10.12-x86_64.egg",
    "./eggs/rfc3987-1.3.5-py3.6.egg",
    "./eggs/rdflib_jsonld-0.3-py3.6.egg",
    "./eggs/rdflib-4.2.2.dev0-py3.6.egg",
    "./eggs/pytz-2016.3-py3.6.egg",
    "/usr/local/lib/python3.6/site-packages",
    "./eggs/pyramid_tm-0.12.1-py3.6.egg",
    "./eggs/pyramid_multiauth-0.8.0-py3.6.egg",
    "./eggs/pyramid_localroles-0.1-py3.6.egg",
    "./eggs/psutil-4.1.0-py3.6-macosx-10.12-x86_64.egg",
    "./eggs/passlib-1.6.5-py3.6.egg",
    "./eggs/cryptacular-1.4.1-py3.6-macosx-10.12-x86_64.egg",
    "./eggs/bcrypt-2.0.0-py3.6-macosx-10.12-x86_64.egg",
    "./eggs/netaddr-0.7.18-py3.6.egg",
    "./eggs/loremipsum-1.0.5-py3.6.egg",
    "./eggs/jsonschema_serialize_fork-2.1.1-py3.6.egg",
    "./eggs/humanfriendly-1.44.5-py3.6.egg",
    "./eggs/future-0.15.2-py3.6.egg",
    "./eggs/lucenequery-0.1-py3.6.egg",
    "./eggs/elasticsearch-2.3.0-py3.6.egg",
    "./eggs/boto3-1.4.4-py3.6.egg",
    "./eggs/jmespath-0.9.0-py3.6.egg",
    "./eggs/botocore-1.5.7-py3.6.egg",
    "./eggs/boto-2.45.0-py3.6.egg",
    "./eggs/WebTest-2.0.20-py3.6.egg",
    "./eggs/WSGIProxy2-0.4.2-py3.6.egg",
    "./eggs/SQLAlchemy-1.0.12-py3.6-macosx-10.12-x86_64.egg",
    "./eggs/PyBrowserID-0.10.0-py3.6.egg",
    "./eggs/Pillow-3.1.1-py3.6-macosx-10.12-x86_64.egg",
    "./develop/snovault/src",
    "./eggs/keepalive-0.5-py3.6.egg",
    "./eggs/transaction-1.4.4-py3.6.egg",
    "./eggs/pyparsing-2.1.1-py3.6.egg",
    "./eggs/isodate-0.5.4-py3.6.egg",
    "./eggs/pbkdf2-1.3-py3.6.egg",
    "./eggs/cffi-1.6.0-py3.6-macosx-10.12-x86_64.egg",
    "./eggs/antlr4_python3_runtime-4.5.2.1-py3.6.egg",
    "./eggs/urllib3-1.14-py3.6.egg",
    "./eggs/docutils-0.12-py3.6.egg",
    "./eggs/python_dateutil-2.5.1-py3.6.egg",
    "./eggs/beautifulsoup4-4.4.1-py3.6.egg",
    "./eggs/requests-2.9.1-py3.6.egg",
    "./eggs/awscli-1.11.44-py3.6.egg",
    "./eggs/pycparser-2.14-py3.6.egg",
    "./eggs/rsa-3.3-py3.6.egg",
    "./eggs/colorama-0.3.3-py3.6.egg",
    "./eggs/pyasn1-0.1.9-py3.6.egg",
]
