branch-defaults:
  FF-687:
    ec2_keyname: alexkb
    environment: 4dn-web-alex-2
  aws_beanstalk:
    environment: 4dn-web-prod
    group_suffix: null
  fix_404_no_auth:
    environment: 4dn-web-alex
  master:
    environment: fourfront-webprod
  production:
    environment: fourfront-webprod
global:
  application_name: 4dn-web
  default_ec2_keyname: 4dn-encode
  default_platform: Python 3.4
  default_region: us-east-1
  profile: null
  sc: git
